window.level6Questions = [
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Chu vi hình chữ nhật dài 7 cm, rộng 11 cm là bao nhiêu cm?', answer: 36, topic: 'Chu vi' },
  { prompt: 'Hình tam giác có mấy cạnh?', answer: 3, topic: 'Hình học' },
  { prompt: 'Có 4 hình vuông. Hỏi có tất cả bao nhiêu góc?', answer: 16, topic: 'Đếm góc' },
  { prompt: 'Hình vuông có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Chu vi hình chữ nhật dài 11 cm, rộng 5 cm là bao nhiêu cm?', answer: 32, topic: 'Chu vi' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Có 14 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 42, topic: 'Đếm cạnh' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Chu vi hình vuông có cạnh 16 cm là bao nhiêu cm?', answer: 64, topic: 'Chu vi' },
  { prompt: 'Hình vuông có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Chu vi hình chữ nhật dài 7 cm, rộng 10 cm là bao nhiêu cm?', answer: 34, topic: 'Chu vi' },
  { prompt: 'Có 14 hình vuông. Hỏi có tất cả bao nhiêu góc?', answer: 56, topic: 'Đếm góc' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Có 2 hình vuông. Hỏi có tất cả bao nhiêu góc?', answer: 8, topic: 'Đếm góc' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy cạnh?', answer: 3, topic: 'Hình học' },
  { prompt: 'Có 6 hình vuông. Hỏi có tất cả bao nhiêu góc?', answer: 24, topic: 'Đếm góc' },
  { prompt: 'Chu vi hình vuông có cạnh 12 cm là bao nhiêu cm?', answer: 48, topic: 'Chu vi' },
  { prompt: 'Chu vi hình chữ nhật dài 8 cm, rộng 5 cm là bao nhiêu cm?', answer: 26, topic: 'Chu vi' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Có 15 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 45, topic: 'Đếm cạnh' },
  { prompt: 'Chu vi hình vuông có cạnh 5 cm là bao nhiêu cm?', answer: 20, topic: 'Chu vi' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Chu vi hình vuông có cạnh 11 cm là bao nhiêu cm?', answer: 44, topic: 'Chu vi' },
  { prompt: 'Hình vuông có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Có 13 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 39, topic: 'Đếm cạnh' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Có 14 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 42, topic: 'Đếm cạnh' },
  { prompt: 'Chu vi hình chữ nhật dài 12 cm, rộng 4 cm là bao nhiêu cm?', answer: 32, topic: 'Chu vi' },
  { prompt: 'Chu vi hình chữ nhật dài 21 cm, rộng 8 cm là bao nhiêu cm?', answer: 58, topic: 'Chu vi' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy cạnh?', answer: 3, topic: 'Hình học' },
  { prompt: 'Có 13 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 39, topic: 'Đếm cạnh' },
  { prompt: 'Có 7 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 21, topic: 'Đếm cạnh' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy cạnh?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Chu vi hình chữ nhật dài 9 cm, rộng 11 cm là bao nhiêu cm?', answer: 40, topic: 'Chu vi' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy cạnh?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Chu vi hình chữ nhật dài 18 cm, rộng 4 cm là bao nhiêu cm?', answer: 44, topic: 'Chu vi' },
  { prompt: 'Hình tam giác có mấy cạnh?', answer: 3, topic: 'Hình học' },
  { prompt: 'Có 1 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 3, topic: 'Đếm cạnh' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Có 15 hình vuông. Hỏi có tất cả bao nhiêu góc?', answer: 60, topic: 'Đếm góc' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Chu vi hình vuông có cạnh 13 cm là bao nhiêu cm?', answer: 52, topic: 'Chu vi' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Có 12 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 36, topic: 'Đếm cạnh' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Chu vi hình chữ nhật dài 17 cm, rộng 7 cm là bao nhiêu cm?', answer: 48, topic: 'Chu vi' },
  { prompt: 'Có 2 hình vuông. Hỏi có tất cả bao nhiêu góc?', answer: 8, topic: 'Đếm góc' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình vuông có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Chu vi hình chữ nhật dài 17 cm, rộng 10 cm là bao nhiêu cm?', answer: 54, topic: 'Chu vi' },
  { prompt: 'Chu vi hình vuông có cạnh 7 cm là bao nhiêu cm?', answer: 28, topic: 'Chu vi' },
  { prompt: 'Có 10 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 30, topic: 'Đếm cạnh' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình tam giác có mấy cạnh?', answer: 3, topic: 'Hình học' },
  { prompt: 'Chu vi hình chữ nhật dài 10 cm, rộng 11 cm là bao nhiêu cm?', answer: 42, topic: 'Chu vi' },
  { prompt: 'Có 10 hình vuông. Hỏi có tất cả bao nhiêu góc?', answer: 40, topic: 'Đếm góc' },
  { prompt: 'Hình vuông có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Chu vi hình chữ nhật dài 18 cm, rộng 11 cm là bao nhiêu cm?', answer: 58, topic: 'Chu vi' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Có 3 hình tam giác. Hỏi có tất cả bao nhiêu cạnh?', answer: 9, topic: 'Đếm cạnh' },
  { prompt: 'Có 3 hình vuông. Hỏi có tất cả bao nhiêu góc?', answer: 12, topic: 'Đếm góc' },
  { prompt: 'Hình tam giác có mấy góc?', answer: 3, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy góc?', answer: 4, topic: 'Hình học' },
  { prompt: 'Hình chữ nhật có mấy cạnh?', answer: 4, topic: 'Hình học' },
];
