window.level5Questions = [
  { prompt: 'Một cửa hàng có 42 chiếc bánh. Đã bán 12 chiếc bánh. Hỏi cửa hàng còn bao nhiêu chiếc bánh?', answer: 30, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 64 quyển vở vào buổi sáng và 30 quyển vở vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu quyển vở?', answer: 94, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 85 bông hoa. Đã bán 30 bông hoa. Hỏi cửa hàng còn bao nhiêu bông hoa?', answer: 55, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 114 chiếc kẹo. Đã bán 24 chiếc kẹo. Hỏi cửa hàng còn bao nhiêu chiếc kẹo?', answer: 90, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 63 quyển vở vào buổi sáng và 27 quyển vở vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu quyển vở?', answer: 90, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 108 quyển sách. Mua thêm 35 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 143, topic: 'Bài toán có lời văn' },
  { prompt: 'Bình có 31 quyển sách. Huy có 13 quyển sách. Cả hai có tất cả bao nhiêu quyển sách?', answer: 44, topic: 'Bài toán có lời văn' },
  { prompt: 'Linh có 38 quả cam. Linh có 22 quả cam. Cả hai có tất cả bao nhiêu quả cam?', answer: 60, topic: 'Bài toán có lời văn' },
  { prompt: 'Nam có 20 quyển sách. Nam sử dụng hết 7 quyển sách. Hỏi còn lại bao nhiêu quyển sách?', answer: 13, topic: 'Bài toán có lời văn' },
  { prompt: 'Huy có 56 cây bút. Huy sử dụng hết 7 cây bút. Hỏi còn lại bao nhiêu cây bút?', answer: 49, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 119 quả bóng. Đã bán 28 quả bóng. Hỏi cửa hàng còn bao nhiêu quả bóng?', answer: 91, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 27 cây bút vào buổi sáng và 40 cây bút vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu cây bút?', answer: 67, topic: 'Bài toán có lời văn' },
  { prompt: 'Nam có 62 quyển sách. Nam cho bạn 11 quyển sách. Nam còn lại bao nhiêu quyển sách?', answer: 51, topic: 'Bài toán có lời văn' },
  { prompt: 'Phúc mua 30 cây bút, sau đó mua thêm 27 cây bút. Hỏi Phúc có bao nhiêu cây bút?', answer: 57, topic: 'Bài toán có lời văn' },
  { prompt: 'Huy có 36 quyển vở. Huy sử dụng hết 12 quyển vở. Hỏi còn lại bao nhiêu quyển vở?', answer: 24, topic: 'Bài toán có lời văn' },
  { prompt: 'Linh có 29 quyển sách. Linh sử dụng hết 9 quyển sách. Hỏi còn lại bao nhiêu quyển sách?', answer: 20, topic: 'Bài toán có lời văn' },
  { prompt: 'Hoa có 46 cây bút. Hoa cho bạn 5 cây bút. Hoa còn lại bao nhiêu cây bút?', answer: 41, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 25 quả bóng vào buổi sáng và 44 quả bóng vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu quả bóng?', answer: 69, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 82 quyển vở vào buổi sáng và 35 quyển vở vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu quyển vở?', answer: 117, topic: 'Bài toán có lời văn' },
  { prompt: 'Bình mua 14 quyển vở, sau đó mua thêm 2 quyển vở. Hỏi Bình có bao nhiêu quyển vở?', answer: 16, topic: 'Bài toán có lời văn' },
  { prompt: 'Hoa mua 38 quả táo, sau đó mua thêm 2 quả táo. Hỏi Hoa có bao nhiêu quả táo?', answer: 40, topic: 'Bài toán có lời văn' },
  { prompt: 'Hoa có 11 quyển vở. Nam có 35 quyển vở. Cả hai có tất cả bao nhiêu quyển vở?', answer: 46, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 116 quyển sách. Mua thêm 37 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 153, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 76 cây bút vào buổi sáng và 20 cây bút vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu cây bút?', answer: 96, topic: 'Bài toán có lời văn' },
  { prompt: 'Bình có 60 bông hoa. Bình cho bạn 5 bông hoa. Bình còn lại bao nhiêu bông hoa?', answer: 55, topic: 'Bài toán có lời văn' },
  { prompt: 'An mua 14 chiếc kẹo, sau đó mua thêm 21 chiếc kẹo. Hỏi An có bao nhiêu chiếc kẹo?', answer: 35, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 88 quyển sách. Mua thêm 13 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 101, topic: 'Bài toán có lời văn' },
  { prompt: 'Lan có 57 chiếc bánh. Lan cho bạn 12 chiếc bánh. Lan còn lại bao nhiêu chiếc bánh?', answer: 45, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 69 quyển sách. Mua thêm 44 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 113, topic: 'Bài toán có lời văn' },
  { prompt: 'Nam có 27 quyển sách. Nam sử dụng hết 9 quyển sách. Hỏi còn lại bao nhiêu quyển sách?', answer: 18, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 136 quyển sách. Mua thêm 40 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 176, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 52 chiếc kẹo. Đã bán 24 chiếc kẹo. Hỏi cửa hàng còn bao nhiêu chiếc kẹo?', answer: 28, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 62 cây bút. Đã bán 21 cây bút. Hỏi cửa hàng còn bao nhiêu cây bút?', answer: 41, topic: 'Bài toán có lời văn' },
  { prompt: 'An mua 30 quả táo, sau đó mua thêm 8 quả táo. Hỏi An có bao nhiêu quả táo?', answer: 38, topic: 'Bài toán có lời văn' },
  { prompt: 'Bình có 48 quả táo. Mẹ cho thêm 23 quả táo. Bình có tất cả bao nhiêu quả táo?', answer: 71, topic: 'Bài toán có lời văn' },
  { prompt: 'Nam có 48 quyển sách. Nam sử dụng hết 5 quyển sách. Hỏi còn lại bao nhiêu quyển sách?', answer: 43, topic: 'Bài toán có lời văn' },
  { prompt: 'Minh có 19 chiếc kẹo. Mai có 19 chiếc kẹo. Cả hai có tất cả bao nhiêu chiếc kẹo?', answer: 38, topic: 'Bài toán có lời văn' },
  { prompt: 'An có 33 chiếc kẹo. Mẹ cho thêm 18 chiếc kẹo. An có tất cả bao nhiêu chiếc kẹo?', answer: 51, topic: 'Bài toán có lời văn' },
  { prompt: 'Minh có 32 chiếc kẹo. Bình có 23 chiếc kẹo. Cả hai có tất cả bao nhiêu chiếc kẹo?', answer: 55, topic: 'Bài toán có lời văn' },
  { prompt: 'Huy có 43 quả cam. Huy cho bạn 16 quả cam. Huy còn lại bao nhiêu quả cam?', answer: 27, topic: 'Bài toán có lời văn' },
  { prompt: 'Lan có 21 quyển vở. Mẹ cho thêm 25 quyển vở. Lan có tất cả bao nhiêu quyển vở?', answer: 46, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 60 chiếc kẹo. Đã bán 20 chiếc kẹo. Hỏi cửa hàng còn bao nhiêu chiếc kẹo?', answer: 40, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 71 quyển sách vào buổi sáng và 20 quyển sách vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu quyển sách?', answer: 91, topic: 'Bài toán có lời văn' },
  { prompt: 'Minh có 37 viên bi. Minh có 23 viên bi. Cả hai có tất cả bao nhiêu viên bi?', answer: 60, topic: 'Bài toán có lời văn' },
  { prompt: 'An mua 23 quả cam, sau đó mua thêm 21 quả cam. Hỏi An có bao nhiêu quả cam?', answer: 44, topic: 'Bài toán có lời văn' },
  { prompt: 'Phúc có 34 quyển vở. Phúc cho bạn 10 quyển vở. Phúc còn lại bao nhiêu quyển vở?', answer: 24, topic: 'Bài toán có lời văn' },
  { prompt: 'Phúc mua 57 cây bút, sau đó mua thêm 27 cây bút. Hỏi Phúc có bao nhiêu cây bút?', answer: 84, topic: 'Bài toán có lời văn' },
  { prompt: 'Mai có 71 chiếc bánh. Mai cho bạn 15 chiếc bánh. Mai còn lại bao nhiêu chiếc bánh?', answer: 56, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 94 chiếc bánh vào buổi sáng và 23 chiếc bánh vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu chiếc bánh?', answer: 117, topic: 'Bài toán có lời văn' },
  { prompt: 'Huy mua 25 quả bóng, sau đó mua thêm 2 quả bóng. Hỏi Huy có bao nhiêu quả bóng?', answer: 27, topic: 'Bài toán có lời văn' },
  { prompt: 'Lan có 43 quả cam. Lan sử dụng hết 18 quả cam. Hỏi còn lại bao nhiêu quả cam?', answer: 25, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 94 quả bóng. Đã bán 22 quả bóng. Hỏi cửa hàng còn bao nhiêu quả bóng?', answer: 72, topic: 'Bài toán có lời văn' },
  { prompt: 'Phúc có 39 chiếc bánh. Phúc có 24 chiếc bánh. Cả hai có tất cả bao nhiêu chiếc bánh?', answer: 63, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 96 quả cam. Đã bán 32 quả cam. Hỏi cửa hàng còn bao nhiêu quả cam?', answer: 64, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 109 quyển sách. Mua thêm 20 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 129, topic: 'Bài toán có lời văn' },
  { prompt: 'Hoa có 24 viên bi. Mẹ cho thêm 9 viên bi. Hoa có tất cả bao nhiêu viên bi?', answer: 33, topic: 'Bài toán có lời văn' },
  { prompt: 'Bình có 62 viên bi. Bình cho bạn 11 viên bi. Bình còn lại bao nhiêu viên bi?', answer: 51, topic: 'Bài toán có lời văn' },
  { prompt: 'Linh có 37 chiếc bánh. Linh sử dụng hết 9 chiếc bánh. Hỏi còn lại bao nhiêu chiếc bánh?', answer: 28, topic: 'Bài toán có lời văn' },
  { prompt: 'Mai có 13 quyển vở. Mẹ cho thêm 18 quyển vở. Mai có tất cả bao nhiêu quyển vở?', answer: 31, topic: 'Bài toán có lời văn' },
  { prompt: 'Huy có 24 bông hoa. Mẹ cho thêm 2 bông hoa. Huy có tất cả bao nhiêu bông hoa?', answer: 26, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 67 quyển sách. Mua thêm 43 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 110, topic: 'Bài toán có lời văn' },
  { prompt: 'Minh mua 41 quyển sách, sau đó mua thêm 19 quyển sách. Hỏi Minh có bao nhiêu quyển sách?', answer: 60, topic: 'Bài toán có lời văn' },
  { prompt: 'Mai có 46 chiếc bánh. Mẹ cho thêm 20 chiếc bánh. Mai có tất cả bao nhiêu chiếc bánh?', answer: 66, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 126 quyển sách. Mua thêm 28 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 154, topic: 'Bài toán có lời văn' },
  { prompt: 'Bình có 19 quyển vở. Mẹ cho thêm 1 quyển vở. Bình có tất cả bao nhiêu quyển vở?', answer: 20, topic: 'Bài toán có lời văn' },
  { prompt: 'Minh có 28 quyển sách. Minh sử dụng hết 11 quyển sách. Hỏi còn lại bao nhiêu quyển sách?', answer: 17, topic: 'Bài toán có lời văn' },
  { prompt: 'Linh có 52 quả táo. Linh sử dụng hết 10 quả táo. Hỏi còn lại bao nhiêu quả táo?', answer: 42, topic: 'Bài toán có lời văn' },
  { prompt: 'Nam có 38 viên bi. Lan có 29 viên bi. Cả hai có tất cả bao nhiêu viên bi?', answer: 67, topic: 'Bài toán có lời văn' },
  { prompt: 'Phúc có 76 chiếc bánh. Phúc cho bạn 7 chiếc bánh. Phúc còn lại bao nhiêu chiếc bánh?', answer: 69, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 144 quyển sách. Mua thêm 14 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 158, topic: 'Bài toán có lời văn' },
  { prompt: 'Bình có 73 chiếc bánh. Bình cho bạn 6 chiếc bánh. Bình còn lại bao nhiêu chiếc bánh?', answer: 67, topic: 'Bài toán có lời văn' },
  { prompt: 'Mai mua 38 quyển sách, sau đó mua thêm 18 quyển sách. Hỏi Mai có bao nhiêu quyển sách?', answer: 56, topic: 'Bài toán có lời văn' },
  { prompt: 'Lan có 35 bông hoa. Huy có 29 bông hoa. Cả hai có tất cả bao nhiêu bông hoa?', answer: 64, topic: 'Bài toán có lời văn' },
  { prompt: 'Phúc có 35 quyển vở. Mẹ cho thêm 16 quyển vở. Phúc có tất cả bao nhiêu quyển vở?', answer: 51, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 106 quyển sách. Mua thêm 39 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 145, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 62 quyển vở vào buổi sáng và 19 quyển vở vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu quyển vở?', answer: 81, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 66 cây bút. Đã bán 38 cây bút. Hỏi cửa hàng còn bao nhiêu cây bút?', answer: 28, topic: 'Bài toán có lời văn' },
  { prompt: 'Nam có 13 viên bi. Mẹ cho thêm 3 viên bi. Nam có tất cả bao nhiêu viên bi?', answer: 16, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 87 quả cam vào buổi sáng và 22 quả cam vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu quả cam?', answer: 109, topic: 'Bài toán có lời văn' },
  { prompt: 'Phúc có 22 chiếc kẹo. Phúc sử dụng hết 19 chiếc kẹo. Hỏi còn lại bao nhiêu chiếc kẹo?', answer: 3, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 114 quyển sách. Mua thêm 25 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 139, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 51 chiếc bánh vào buổi sáng và 29 chiếc bánh vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu chiếc bánh?', answer: 80, topic: 'Bài toán có lời văn' },
  { prompt: 'Nam có 55 quyển vở. Nam sử dụng hết 17 quyển vở. Hỏi còn lại bao nhiêu quyển vở?', answer: 38, topic: 'Bài toán có lời văn' },
  { prompt: 'Linh có 21 cây bút. Hoa có 33 cây bút. Cả hai có tất cả bao nhiêu cây bút?', answer: 54, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 118 quyển sách. Mua thêm 42 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 160, topic: 'Bài toán có lời văn' },
  { prompt: 'Minh có 23 quyển sách. Hoa có 22 quyển sách. Cả hai có tất cả bao nhiêu quyển sách?', answer: 45, topic: 'Bài toán có lời văn' },
  { prompt: 'Mai có 34 quả cam. Bình có 37 quả cam. Cả hai có tất cả bao nhiêu quả cam?', answer: 71, topic: 'Bài toán có lời văn' },
  { prompt: 'Lan có 40 quả bóng. Lan cho bạn 21 quả bóng. Lan còn lại bao nhiêu quả bóng?', answer: 19, topic: 'Bài toán có lời văn' },
  { prompt: 'Mai có 36 cây bút. Mai sử dụng hết 8 cây bút. Hỏi còn lại bao nhiêu cây bút?', answer: 28, topic: 'Bài toán có lời văn' },
  { prompt: 'Linh có 12 chiếc bánh. Hoa có 21 chiếc bánh. Cả hai có tất cả bao nhiêu chiếc bánh?', answer: 33, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 86 viên bi vào buổi sáng và 43 viên bi vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu viên bi?', answer: 129, topic: 'Bài toán có lời văn' },
  { prompt: 'Nam mua 13 cây bút, sau đó mua thêm 18 cây bút. Hỏi Nam có bao nhiêu cây bút?', answer: 31, topic: 'Bài toán có lời văn' },
  { prompt: 'Phúc có 73 viên bi. Phúc cho bạn 21 viên bi. Phúc còn lại bao nhiêu viên bi?', answer: 52, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 129 quyển sách. Mua thêm 55 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 184, topic: 'Bài toán có lời văn' },
  { prompt: 'Thư viện có 63 quyển sách. Mua thêm 13 quyển sách. Hỏi thư viện hiện có bao nhiêu quyển sách?', answer: 76, topic: 'Bài toán có lời văn' },
  { prompt: 'An có 16 bông hoa. Hoa có 18 bông hoa. Cả hai có tất cả bao nhiêu bông hoa?', answer: 34, topic: 'Bài toán có lời văn' },
  { prompt: 'Mai có 47 chiếc bánh. Mai sử dụng hết 14 chiếc bánh. Hỏi còn lại bao nhiêu chiếc bánh?', answer: 33, topic: 'Bài toán có lời văn' },
  { prompt: 'Một cửa hàng có 93 quyển sách. Đã bán 27 quyển sách. Hỏi cửa hàng còn bao nhiêu quyển sách?', answer: 66, topic: 'Bài toán có lời văn' },
  { prompt: 'An có 22 quyển sách. Mẹ cho thêm 12 quyển sách. An có tất cả bao nhiêu quyển sách?', answer: 34, topic: 'Bài toán có lời văn' },
  { prompt: 'Một vườn cây thu hoạch được 72 quả bóng vào buổi sáng và 25 quả bóng vào buổi chiều. Hỏi cả ngày thu hoạch được bao nhiêu quả bóng?', answer: 97, topic: 'Bài toán có lời văn' },
];
